<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mlcp.Domain\Mlcp.Domain.csproj" />
    <ProjectReference Include="..\..\src\Mlcp.Shared\Mlcp.Shared.csproj" />
    <ProjectReference Include="..\..\src\Mlcp.Application\Mlcp.Application.csproj" />
    <ProjectReference Include="..\..\src\Mlcp.Persistence\Mlcp.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Mlcp.Sync\Mlcp.Sync.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

</Project>
