// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mlcp.Persistence;

#nullable disable

namespace Mlcp.Persistence.Migrations
{
    [DbContext(typeof(MlcpDbContext))]
    [Migration("20260902031657_InitialTenancyAndOperations")]
    partial class InitialTenancyAndOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mlcp.Domain.Audit.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<Guid?>("ActorObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorUpn")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("FinancialImpactAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("FinancialImpactCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AuditLogId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TenantId", "OccurredUtc")
                        .IsDescending(false, true);

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Mlcp.Domain.Capabilities.TenantCapabilityProfile", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastProfiledUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NextProfileUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatusesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Statuses");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TenantId");

                    b.HasIndex("NextProfileUtc");

                    b.ToTable("TenantCapabilityProfile", (string)null);
                });

            modelBuilder.Entity("Mlcp.Domain.Sync.SyncRun", b =>
                {
                    b.Property<Guid>("SyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContinuationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ValidationNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("SyncRunId");

                    b.HasIndex("TenantId", "JobType", "StartedUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("SyncRun", (string)null);
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.AppUser", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("EntraObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSubscriptionManager")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScopeSubscriptionIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ScopeSubscriptionIds");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Upn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("AppUserId");

                    b.HasIndex("TenantId", "EntraObjectId")
                        .IsUnique();

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.OnboardingStep", b =>
                {
                    b.Property<Guid>("OnboardingStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OnboardingStepId");

                    b.HasIndex("TenantId", "Step")
                        .IsUnique();

                    b.ToTable("OnboardingStep", (string)null);
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.Organization", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HomeTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("OrganizationId");

                    b.HasIndex("HomeTenantId");

                    b.ToTable("Organization", (string)null);
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.PendingConsentRequest", b =>
                {
                    b.Property<Guid>("PendingConsentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSentUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestedByObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestedByUpn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SendCount")
                        .HasColumnType("int");

                    b.Property<string>("SentToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PendingConsentRequestId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TenantId", "ExpiresUtc");

                    b.ToTable("PendingConsentRequest", (string)null);
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgreementTypePrimary")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ConsentGrantedByObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsentGrantedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultDomain")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DeleteScheduledUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPartnerManaged")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagingPartnerTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TenantId");

                    b.HasIndex("DeleteScheduledUtc")
                        .HasFilter("[DeleteScheduledUtc] IS NOT NULL");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Status");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("Mlcp.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("Mlcp.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mlcp.Domain.Capabilities.TenantCapabilityProfile", b =>
                {
                    b.HasOne("Mlcp.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mlcp.Domain.Sync.SyncRun", b =>
                {
                    b.HasOne("Mlcp.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.AppUser", b =>
                {
                    b.HasOne("Mlcp.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.OnboardingStep", b =>
                {
                    b.HasOne("Mlcp.Domain.Tenancy.Tenant", null)
                        .WithMany("OnboardingSteps")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.PendingConsentRequest", b =>
                {
                    b.HasOne("Mlcp.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.Tenant", b =>
                {
                    b.HasOne("Mlcp.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Mlcp.Domain.Tenancy.Tenant", b =>
                {
                    b.Navigation("OnboardingSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
